/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Q1 */

#ifndef _Included_Q1
#define _Included_Q1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Q1
 * Method:    calcDiloma
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_Q1_calcDiloma
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     Q1
 * Method:    calcDegree
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_Q1_calcDegree
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
