/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Q2 */

#ifndef _Included_Q2
#define _Included_Q2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Q2
 * Method:    randomArr
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_Q2_randomArr
  (JNIEnv *, jobject, jint);

/*
 * Class:     Q2
 * Method:    calcDiff
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Q2_calcDiff
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
